### ISSUE TITLE
📝 🐏 Update GitHub Issue Forms

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/cloud-operations#139]
### User Story

As a… consumer of the cloud operations repositories
I need/want/expect to… have uniform GitHub Issue forms
So that… I can reap all of the benefits compared the manual form

### Useful Contacts

Gary Henderson

### Additional Information

Note [this](https://github.com/github/feedback/discussions/4264) discussion regarding internal / private repositories.

### Definition of Done

The below repos cannot have this implemented at the moment as the feature is only available in pub repositories.

- [x]  ministryofjustice/staff-device-private-dns-zone (internal)
- [x]  ministryofjustice/staff-infrastructure-certificate-services (internal)
- [x]  ministryofjustice/staff-infrastructure-metric-aggregation-server (internal)
- [x]  ministryofjustice/staff-infrastructure-metric-aggregator-cloud (internal)
- [x]  ministryofjustice/staff-infrastructure-monitoring-config (internal)
- [x]  ministryofjustice/staff-infrastructure-monitoring-snmpexporter (internal)
- [x]  ministryofjustice/staff-infrastructure-network-services (internal)

All our repositories
- [x]  ministryofjustice/cloud-operations (public)
- [x]  ministryofjustice/cloud-operations-slack-bot (public)
- [x]  ministryofjustice/network-access-control-admin (public)
- [x]  ministryofjustice/network-access-control-disaster-recovery (public)
- [x]  ministryofjustice/network-access-control-infrastructure (public)
- [x]  ministryofjustice/network-access-control-integration-tests (public)
- [x]  ministryofjustice/network-access-control-server (public)
- [x]  ministryofjustice/staff-device-dhcp-server (public)
- [x]  ministryofjustice/staff-device-dns-dhcp-admin (public)
- [x]  ministryofjustice/staff-device-dns-dhcp-infrastructure (public)
- [x]  ministryofjustice/staff-device-dns-server (public)
- [x]  ministryofjustice/staff-device-docker-base-images (public)
- [x]  ministryofjustice/staff-device-logging-infrastructure (public)
- [x]  ministryofjustice/staff-device-logging-syslog-to-cloudwatch (public)
- [x]  ministryofjustice/staff-device-shared-services-infrastructure (public)
- [x]  ministryofjustice/staff-infrastructure-monitoring (public)
- [x]  ministryofjustice/staff-infrastructure-monitoring-app-reachability (public)
- [x]  ministryofjustice/staff-infrastructure-monitoring-blackbox-exporter (public)
- [x]  ministryofjustice/staff-infrastructure-monitoring-config (internal)
- [x]  ministryofjustice/staff-infrastructure-monitoring-deployments (public)
- [x]  ministryofjustice/staff-infrastructure-network-services (internal)
- [x]  ministryofjustice/staff-infrastructure-smtp-relay-server (public)

**Comment by Gary-H9** [comment]
Call scheduled at 10am on the 5th of May with ZenHub to ask why New Issue button in ZenHub fails to show any of the new Issue Forms. Not a major issue as you can still create an issue using the new form in the GitHub page.

**Comment by Gary-H9** [comment]
I spoke to ZenHub there and they will not be doing any development on the GitHub Issue Forms from their side until its out of Beta from GitHub. We will not be rolling this feature back as we can still create issues from repos themselves.
